#! /usr/bin/env bash

# How frequently to check if the working tree has changed.
TICK_RATE=1
# How many ticks to wait for changes to settle before cutting a commit.
FUSE_TIME=24
# Animation to present while waiting for changes.
SPINNER_FRAMES=(
  $'\e[1;93m'"^('-')^"$'\e[0m'
  $'\e[1;93m'"v('-')v"$'\e[0m')

# Exit if any non-test commands fail
set -e

# Hide all keystrokes while this command is running
stty -echo

autocommit () {
  if [[ -n "$MESSAGE_COMMAND" ]]; then
    git commit -m "$($MESSAGE_COMMAND)" && git push
  else
    git commit -m "Autocommit" && git push
  fi
}

unstaged-changes () {
  git status --porcelain | grep -q '^.[^ ]'
}

uncommitted-changes () {
  local dirt=$(git ls-files -dmo --exclude-standard)
  [[ -n "$dirt" ]]
}

key-pressed-in-tick () {
  local _
  read -s -r -t "$TICK" -n 1 _
}

flush-input () {
  local _
  while read -r -t 0 _; do read -n 4096 -r _; done
}

roll-index () {
  local idle_ticks

  flush-input

  while ((idle_ticks <= FUSE_TIME)); do

    if unstaged-changes; then
      git add -A
      idle_ticks=0
    fi

    echo -n $'\r'"Building commit"
    for ((i = 0; i < FUSE_TIME; ++i)); do
      if ((i < idle_ticks)); then
        echo -n '.'
      else
        echo -n ' '
      fi
    done
    echo -n $'\e[1;31m!\e[0m \e[K'

    idle_ticks=$((idle_ticks + 1))
    if ((idle_ticks <= FUSE_TIME)); then
      if key-pressed-in-tick; then
        git add -A
        idle_ticks=$FUSE_TIME
      fi
    fi

  done
  echo
}

watch-for-changes () {
  local spinstep=0

  while :; do
    echo -n $'\r'"Watching for changes... ${SPINNER_FRAMES[spinstep]} "$'\e[K'

    spinstep=$(( (spinstep + 1) % ${#SPINNER_FRAMES[@]} ))

    if uncommitted-changes; then
      echo
      roll-index
      autocommit
    else
      sleep "$TICK"
    fi
  done
}

if uncommitted-changes; then
  roll-index
  autocommit
fi
watch-for-changes
